### ISSUE TITLE
paddlefx编译错误

### ISSUE THREAD

**Issue by yangguohao** [PFCCLab/paddlefx#63]
在执行 pip install -e . 的时候出现以下错误

```
Building wheels for collected packages: paddlefx
  Building editable for paddlefx (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for paddlefx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running editable_wheel
      creating C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info
      writing C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info\PKG-INFO
      writing dependency_links to C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info\dependency_links.txt
      writing requirements to C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info\requires.txt
      writing top-level names to C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info\top_level.txt
      writing manifest file 'C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info\SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx.egg-info\SOURCES.txt'
      creating 'C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx-0.1.dev41+g61d83da.dist-info'
      C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\wheel\bdist_wheel.py:100: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
      creating C:\Users\62367\AppData\Local\Temp\pip-wheel-hkswl1ei\.tmp-vuf77yaa\paddlefx-0.1.dev41+g61d83da.dist-info\WHEEL
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 72, in build_extensions
        File "<string>", line 30, in _run_cmd
        File "C:\Users\62367\.conda\envs\Interpretor\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\62367\.conda\envs\Interpretor\lib\subprocess.py", line 1436, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 3] 系统找不到指定的路径。
      C:\Users\62367\AppData\Local\Temp\pip-build-env-g0lch0jq\overlay\Lib\site-packages\setuptools\_distutils\dist.py:988: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `paddlefx` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      error: [WinError 3] 系统找不到指定的路径。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for paddlefx
Failed to build paddlefx
ERROR: Could not build wheels for paddlefx, which is required to install pyproject.toml-based projects
```

**Comment by gglin001** [comment]
这个看起来是在 win 平台上, 我没有在 win 上测试过


你可以贴一下
```
pip install -vvv -e .
```

产生的详细的 错误log 吗?

**Comment by yangguohao** [comment]
```
Using pip 23.1.2 from C:\Users\62367\.conda\envs\Interpretor\lib\site-packages\pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-build-tracker-0d6ds3yd
Initialized build tracking at C:\Users\62367\AppData\Local\Temp\pip-build-tracker-0d6ds3yd
Created build tracker: C:\Users\62367\AppData\Local\Temp\pip-build-tracker-0d6ds3yd
Entered build tracker: C:\Users\62367\AppData\Local\Temp\pip-build-tracker-0d6ds3yd
Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-install-5jsnmraa
Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-ephem-wheel-cache-o5ay7pl0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///C:/Users/62367/pythonProject/paddlefx
  Added file:///C:/Users/62367/pythonProject/paddlefx to build tracker 'C:\\Users\\62367\\AppData\\Local\\Temp\\pip-build-tracker-0d6ds3yd'
  Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh
  Running command pip subprocess to install build dependencies
  Using pip 23.1.2 from C:\Users\62367\.conda\envs\Interpretor\Lib\site-packages\pip (python 3.9)
  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Collecting setuptools>=45
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl (804 kB)
  Collecting wheel
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/17/11/f139e25018ea2218aeedbedcf85cd0dd8abeed29a38ac1fda7f5a8889382/wheel-0.41.0-py3-none-any.whl (64 kB)
  Collecting setuptools_scm[toml]>=6.2
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1d/66/8f42c941be949ef2b22fe905d850c794e7c170a526023612aad5f3a121ad/setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
  Collecting ninja==1.11.1
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9d/74/71ef16dea18414acf7ca0da7a16e2fcb9f73d7a16d00879aed385840c720/ninja-1.11.1-py2.py3-none-win_amd64.whl (313 kB)
  Collecting cmake>=3.25.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/78/cf/42d206fc2679902e9408688a6e75215215e7781faf88653b2738c599e70a/cmake-3.27.0-py2.py3-none-win_amd64.whl (34.6 MB)
  Collecting mypy==1.0.0
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d1/2b/732ab91b85715371a6499272c8884f3473a95dbe4ad5d2829b25c8bf18c8/mypy-1.0.0-cp39-cp39-win_amd64.whl (8.8 MB)
  Collecting typing-extensions>=3.10 (from mypy==1.0.0)
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl (33 kB)
  Collecting mypy-extensions>=0.4.3 (from mypy==1.0.0)
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
  Collecting tomli>=1.1.0 (from mypy==1.0.0)
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting packaging>=20.0 (from setuptools_scm[toml]>=6.2)
    Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl (48 kB)
  Installing collected packages: ninja, cmake, wheel, typing-extensions, tomli, setuptools, packaging, mypy-extensions, setuptools_scm, mypy
    Creating C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Scripts
  Successfully installed cmake-3.27.0 mypy-1.0.0 mypy-extensions-1.0.0 ninja-1.11.1 packaging-23.1 setuptools-68.0.0 setuptools_scm-7.1.0 tomli-2.0.1 typing-extensions-4.7.1 wheel-0.41.0
  Installing build dependencies ... done
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Getting requirements to build editable
  running egg_info
  writing src\paddlefx.egg-info\PKG-INFO
  writing dependency_links to src\paddlefx.egg-info\dependency_links.txt
  writing requirements to src\paddlefx.egg-info\requires.txt
  writing top-level names to src\paddlefx.egg-info\top_level.txt
  adding license file 'LICENSE'
  writing manifest file 'src\paddlefx.egg-info\SOURCES.txt'
  Getting requirements to build editable ... done
  Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y
  Running command Preparing editable metadata (pyproject.toml)
  running dist_info
  creating C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info
  writing C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info\PKG-INFO
  writing dependency_links to C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info\dependency_links.txt
  writing requirements to C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info\requires.txt
  writing top-level names to C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info\top_level.txt
  writing manifest file 'C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx.egg-info\SOURCES.txt'
  creating 'C:\Users\62367\AppData\Local\Temp\pip-modern-metadata-bwds_38y\paddlefx-0.1.dev41+g61d83da.dist-info'
  Preparing editable metadata (pyproject.toml) ... done
  Source in c:\users\62367\pythonproject\paddlefx has version 0.1.dev41+g61d83da, which satisfies requirement paddlefx==0.1.dev41+g61d83da from file:///C:/Users/62367/pythonProject/paddlefx
  Removed paddlefx==0.1.dev41+g61d83da from file:///C:/Users/62367/pythonProject/paddlefx from build tracker 'C:\\Users\\62367\\AppData\\Local\\Temp\\pip-build-tracker-0d6ds3yd'
Requirement already satisfied: paddlepaddle>=2.4.0 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlefx==0.1.dev41+g61d83da) (2.5.1)
Requirement already satisfied: pydot in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlefx==0.1.dev41+g61d83da) (1.4.2)
Requirement already satisfied: httpx in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (0.24.1)
Requirement already satisfied: numpy>=1.13 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (1.25.2)
Requirement already satisfied: Pillow in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (10.0.0)
Requirement already satisfied: decorator in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (5.1.1)
Requirement already satisfied: astor in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (0.8.1)
Requirement already satisfied: paddle-bfloat==0.1.7 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (0.1.7)
Requirement already satisfied: opt-einsum==3.3.0 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (3.3.0)
Requirement already satisfied: protobuf<=3.20.2,>=3.1.0 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (3.20.2)
Requirement already satisfied: pyparsing>=2.1.4 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from pydot->paddlefx==0.1.dev41+g61d83da) (3.1.1)
Requirement already satisfied: certifi in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (2023.7.22)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (0.17.3)
Requirement already satisfied: idna in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (3.4)
Requirement already satisfied: sniffio in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (3.7.1)
Requirement already satisfied: exceptiongroup in c:\users\62367\.conda\envs\interpretor\lib\site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx->paddlepaddle>=2.4.0->paddlefx==0.1.dev41+g61d83da) (1.1.2)
Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-unpack-07m09g3f
Building wheels for collected packages: paddlefx
  Created temporary directory: C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be
  Destination directory: C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be
  Running command Building editable for paddlefx (pyproject.toml)
  running editable_wheel
  creating C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info
  writing C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info\PKG-INFO
  writing dependency_links to C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info\dependency_links.txt
  writing requirements to C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info\requires.txt
  writing top-level names to C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info\top_level.txt
  writing manifest file 'C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info\SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx.egg-info\SOURCES.txt'
  creating 'C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx-0.1.dev41+g61d83da.dist-info'
  C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\wheel\bdist_wheel.py:100: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
    if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
  creating C:\Users\62367\AppData\Local\Temp\pip-wheel-tf4jk7be\.tmp-__ibs1ab\paddlefx-0.1.dev41+g61d83da.dist-info\WHEEL
  running build_py
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 155, in run
      self._create_wheel_file(bdist_wheel)
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 344, in _create_wheel_file
      files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 267, in _run_build_commands
      self._run_build_subcommands()
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 294, in _run_build_subcommands
      self.run_command(name)
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
      super().run_command(command)
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
      self.build_extensions()
    File "<string>", line 72, in build_extensions
    File "<string>", line 30, in _run_cmd
    File "C:\Users\62367\.conda\envs\Interpretor\lib\subprocess.py", line 951, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\62367\.conda\envs\Interpretor\lib\subprocess.py", line 1436, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 3] 系统找不到指定的路径。
  C:\Users\62367\AppData\Local\Temp\pip-build-env-ya5_4nfh\overlay\Lib\site-packages\setuptools\_distutils\dist.py:988: _DebuggingTips: Problem in editable installation.
  !!

          ********************************************************************************
          An error happened while installing `paddlefx` in editable mode.

          The following steps are recommended to help debug this problem:

          - Try to install the project normally, without using the editable mode.
            Does the error still persist?
            (If it does, try fixing the problem before attempting the editable mode).
          - If you are using binary extensions, make sure you have all OS-level
            dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
          - Try the latest version of setuptools (maybe the error was already fixed).
          - If you (or your project dependencies) are using any setuptools extension
            or customization, make sure they support the editable mode.

          After following the steps above, if the problem still persists and
          you think this is related to how setuptools handles editable installations,
          please submit a reproducible example
          (see https://stackoverflow.com/help/minimal-reproducible-example) to:

              https://github.com/pypa/setuptools/issues

          See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
          ********************************************************************************

  !!
    cmd_obj.run()
  error: [WinError 3] 系统找不到指定的路径。
  error: subprocess-exited-with-error

  × Building editable for paddlefx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\62367\.conda\envs\Interpretor\python.exe' 'C:\Users\62367\.conda\envs\Interpretor\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' build_editable 'C:\Users\62367\AppData\Local\Temp\tmpbsg2_7z5'
  cwd: C:\Users\62367\pythonProject\paddlefx
  Building editable for paddlefx (pyproject.toml) ... error
  ERROR: Failed building editable for paddlefx
Failed to build paddlefx
ERROR: Could not build wheels for paddlefx, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "C:\Users\62367\.conda\envs\Interpretor\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\62367\.conda\envs\Interpretor\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "C:\Users\62367\.conda\envs\Interpretor\lib\site-packages\pip\_internal\commands\install.py", line 426, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for paddlefx, which is required to install pyproject.toml-based projects
Remote version of pip: 23.2.1
Local version of pip:  23.1.2
Was pip installed by pip? False
Removed build tracker: 'C:\\Users\\62367\\AppData\\Local\\Temp\\pip-build-tracker-0d6ds3yd'
```
这是我跑了 `pip install -vvv -e .`之后的所有输出。

**Comment by yangguohao** [comment]
是在 win 平台上的

**Comment by gglin001** [comment]
> 是在 win 平台上的

抱歉我没有在 win 上进行类似开发(编译 cpython 插件)的经历, 也许你可以在 win 上使用 wsl 的 linux 环境进行开发

ref
https://learn.microsoft.com/en-us/windows/wsl/install
